export const products = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviews: 128,
    image: "🎧",
    badge: "sale",
    category: "Electronics",
  },
  {
    id: 2,
    name: "Designer Leather Watch",
    price: 189,
    originalPrice: null,
    rating: 4.9,
    reviews: 256,
    image: "⌚",
    badge: "new",
    category: "Accessories",
  },
  {
    id: 3,
    name: "Minimal Sneakers",
    price: 149,
    originalPrice: 199,
    rating: 4.7,
    reviews: 89,
    image: "👟",
    badge: "sale",
    category: "Footwear",
  },
  {
    id: 4,
    name: "Smart Fitness Tracker",
    price: 129,
    originalPrice: null,
    rating: 4.6,
    reviews: 312,
    image: "📱",
    badge: null,
    category: "Electronics",
  },
  {
    id: 5,
    name: "Premium Sunglasses",
    price: 179,
    originalPrice: 229,
    rating: 4.8,
    reviews: 167,
    image: "🕶️",
    badge: "sale",
    category: "Accessories",
  },
  {
    id: 6,
    name: "Leather Backpack",
    price: 259,
    originalPrice: null,
    rating: 4.9,
    reviews: 203,
    image: "🎒",
    badge: "new",
    category: "Bags",
  },
  {
    id: 7,
    name: "Wireless Earbuds Pro",
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviews: 445,
    image: "🎵",
    badge: "sale",
    category: "Electronics",
  },
  {
    id: 8,
    name: "Classic Denim Jacket",
    price: 129,
    originalPrice: null,
    rating: 4.5,
    reviews: 178,
    image: "🧥",
    badge: null,
    category: "Clothing",
  },
];
